### PR TITLE
Fix configurability of codecell

### LINKED ISSUE #7896: Tooltip for class constructors gone in IPython 3.0
The IPython 3.0 upgrade now shows less helpful tooltips. In particular, tooltips for class constructors are now gone.

This is what we get in IPython 2.4:

ipython2 4

And this is what we get now:

ipython3 0

Also worth notice is that auto closing parentheses is also missing in the new version.

### PR DESCRIPTION
**Pull request by Carreau**
code cell where actually not configurable,
this fixes that + add a convenient methods to dump the
content of the configuration in the config file.

this also close #7896 by defaulting closebracket to true,
which is now configurable :-)

It also switches the default magic highlight mode to string so that they
could also be configured.

### CODE REVIEW

File: IPython/html/static/notebook/js/codecell.js [hunk 1]
```diff
@@ -127,25 +127,36 @@ define([
...
 
+    CodeCell.config_defaults = CodeCell.options_default;
+
     CodeCell.msg_cells = {};
 
     CodeCell.prototype = Object.create(Cell.prototype);
+    
+    /**
+     * @private
+     * Update the current state of the config file in the profile with current config.
```
Comment (takluyver) [inline IPython/html/static/notebook/js/codecell.js]: Our general policy is that we don't create config files with the default values, because it makes it harder to change them later. I'm sure there's stuff we need to think more about, but I don't think this is the right approach.

Also, this appears to be a private method, but it's never called.

**Comment by takluyver** [comment]
Does this go into 3.1? Or is it likely to break people's customisation? If we hold it off to 4.0, we should make another PR that just re-enables auto bracket closing.

File: IPython/html/static/notebook/js/codecell.js (hunk 1 above)
Comment (Carreau) [inline IPython/html/static/notebook/js/codecell.js]: The problem is that if you want to change something with current configs, it is **really hard**. With that you can dump easily the current config back to the file.

So by default the file would be empty, but if you call this explicitely, then you "just" have to modify the json on disk.
I can remove it though.

**Comment by Carreau** [comment]
No it wont break people customisation. The thing is with the current state of 3.0 it is **not** configurable with `nbconfig/ntebook.json`

File: IPython/html/static/notebook/js/codecell.js (hunk 1 above)
Comment (takluyver) [inline IPython/html/static/notebook/js/codecell.js]: Perhaps for things like codemirror config, we should merge the user's config with the default, rather than using the user's config *or* the default.

**Comment by takluyver** [comment]
But people may change the options in custom.js - see e.g. #7984.

**Comment by Carreau** [comment]
> But people may change the options in custom.js - see e.g. #7984.

I'm not sure I follow you ? #7984 is already not working.

**Comment by takluyver** [comment]
No, but that's probably just a matter of requiring something or waiting for the relevant event. The CodeCell options can be customised, and people are using that.

**Comment by takluyver** [comment]
Looking at it some more, this shouldn't break the customisation done in #7984. I still think we should think about merging user options for things like cm_config with the default, but that can be a 4.0 thing if you like. In any case, I would get rid of the unused private method before merging this.

**Comment by Carreau** [comment]
> I still think we should think about merging user options for things like cm_config with the default

Not sure what you meant. 

> I would get rid of the unused private method before merging this.

Done.

**Comment by takluyver** [comment]
What I meant about merging: currently we do something like this:

```javascript
cm_config = user_config.cm_config || defaults.cm_config;
```

If we instead do something like this, then writing the defaults to the file would be unnecessary:

```javascript
cm_config = $.extend(defaults.cm_config || {}, userconfig.cm_config);
```

(That code is illustrative, not a real part of the code)

**Comment by takluyver** [comment]
Do you want to look into that in this PR, or leave it for later examination?

**Comment by Carreau** [comment]
> Do you want to look into that in this PR, or leave it for later examination?

Hum, I would do that later. But I can try to make it for 3.1. I'll open a separate issue.

**Comment by minrk** [comment]
Doing it live!
